name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk@v3
        with:
          github_user_name: kelvinhe04
          outputs: |
            dist/github-contribution-grid-snake.svg

      - name: Push snake.svg to output branch
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git clone --depth=1 --branch=output https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} output
          cp dist/* output/
          cd output
          git add .
          git commit -m "update snake contribution graph" || echo "no changes to commit"
          git push
